# Generated by Django 4.1.7 on 2023-04-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
