# Generated by Django 4.1.7 on 2023-04-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
