# Generated by Django 4.1.7 on 2023-06-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_delete_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='baseColour',
            new_name='base_colour',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='masterCategory',
            new_name='master_category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='productDisplayName',
            new_name='product_display_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subCategory',
            new_name='sub_category',
        ),
    ]
