# Generated by Django 4.1.7 on 2023-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0013_item_numreviews_item_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
